/**
 * Downloads the site's webfonts into public/fonts/ and writes fonts.css.
 *
 * Loading these from fonts.googleapis.com costs a render-blocking stylesheet on
 * a third-party origin, plus DNS and TLS to a second origin (fonts.gstatic.com)
 * before a single glyph can paint. That lands directly on LCP, which is the
 * Core Web Vital most likely to be a problem on a type-led page like this one.
 * Self-hosting removes both round-trips.
 *
 * Only the Latin subset is kept — the CDN also serves Vietnamese and Latin-Ext
 * cuts that nothing on this site needs.
 *
 * Run by hand, not by `npm run build`: it needs the network, and the deploy
 * should not. The output is committed. Re-run only to add a weight or a family.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Licensing: Archivo, Instrument Serif and JetBrains Mono are all published
 * under the SIL Open Font License 1.1, which permits self-hosting. See
 * public/fonts/OFL-NOTICE.txt.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

/** Google Fonts serves woff2 only to a browser-shaped User-Agent. */
const CHROME_UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700&family=Instrument+Serif:ital@0;1&family=JetBrains+Mono:wght@400;500&display=swap';

/** The basic-Latin cut always starts at U+0000-00FF. Everything else is dropped. */
const isLatin = (unicodeRange) => unicodeRange.startsWith('U+0000-00FF');

const OUT_DIR = path.resolve('public/fonts');
const CSS_OUT = path.resolve('fonts.css');

const slug = (family, style) =>
  `${family.toLowerCase().replace(/\s+/g, '-')}${style === 'italic' ? '-italic' : ''}`;

const css = await fetch(CSS_URL, { headers: { 'User-Agent': CHROME_UA } }).then((res) => {
  if (!res.ok) throw new Error(`fetch-fonts: font CSS request failed (${res.status})`);
  return res.text();
});

const faces = [...css.matchAll(/@font-face\s*\{([\s\S]*?)\}/g)]
  .map(([, body]) => ({
    family: body.match(/font-family:\s*'([^']+)'/)?.[1],
    style: body.match(/font-style:\s*(\S+?);/)?.[1],
    weight: body.match(/font-weight:\s*(\S+?);/)?.[1],
    url: body.match(/url\((https:\/\/[^)]+)\)/)?.[1],
    range: body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim(),
  }))
  .filter((face) => face.url && face.range && isLatin(face.range));

if (faces.length === 0) {
  throw new Error('fetch-fonts: no Latin faces found — the CDN response format may have changed');
}

/**
 * Several weights of a variable family resolve to the same file. Group by URL so
 * one file is downloaded once and declared with a weight *range*, which is both
 * fewer bytes and fewer requests than one file per weight.
 */
const byUrl = new Map();
for (const face of faces) {
  const key = face.url;
  const entry = byUrl.get(key) ?? { ...face, weights: [] };
  entry.weights.push(Number(face.weight));
  byUrl.set(key, entry);
}

await mkdir(OUT_DIR, { recursive: true });

const declarations = [];

for (const face of byUrl.values()) {
  const weights = [...new Set(face.weights)].sort((a, b) => a - b);
  const name = `${slug(face.family, face.style)}-latin.woff2`;

  const bytes = await fetch(face.url).then(async (res) => {
    if (!res.ok) throw new Error(`fetch-fonts: ${res.status} fetching ${face.url}`);
    return Buffer.from(await res.arrayBuffer());
  });

  await writeFile(path.join(OUT_DIR, name), bytes);

  const weightRule =
    weights.length > 1 ? `${weights[0]} ${weights[weights.length - 1]}` : String(weights[0]);

  declarations.push(
    [
      '@font-face {',
      `  font-family: '${face.family}';`,
      `  font-style: ${face.style};`,
      `  font-weight: ${weightRule};`,
      '  font-display: swap;',
      `  src: url('/fonts/${name}') format('woff2');`,
      `  unicode-range: ${face.range};`,
      '}',
    ].join('\n'),
  );

  console.log(
    `${name.padEnd(34)} ${String(Math.round(bytes.length / 1024)).padStart(3)} kB  weight ${weightRule}`,
  );
}

const header = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.
 *
 * Self-hosted so the critical path does not depend on fonts.googleapis.com.
 * Latin subset only. font-display: swap means text paints immediately in the
 * fallback and reflows once, rather than staying invisible.
 *
 * The families are OFL-1.1; see public/fonts/OFL-NOTICE.txt. */\n\n`;

await writeFile(CSS_OUT, header + declarations.join('\n\n') + '\n');
console.log(`\nwrote ${path.relative(process.cwd(), CSS_OUT)} — ${declarations.length} face(s)`);
